"""followers

Revision ID: 395a36c54981
Revises: 9ad3d08b79a0
Create Date: 2022-04-15 15:29:36.590540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395a36c54981'
down_revision = '9ad3d08b79a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
